* SPARTAN EMACS

Finally, a simple base Emacs configuration framework

** Major update

We now add treesitter support, and have less of a need for "language layers", all configuration should be done in ~/.emacs.d/spartan.el,
which should is mostly self documented.

** FEATURES

- KISS, clean configuration and a comprehensible layers system with minimal abstraction, (easy to hack on to make it "yours.")
- Uses lightweight, mostly-vanilla configured layer packages
- Straight + use-package version version pinning for greater stability (pins are updated here approximately once a month.)
- Popular langs come with optional layers that are preconfigured with eglot LSP and company mode
- Project Awareness is available with Projectile, and Magit
- Everything is deferred as much as is reasonable, for <1 second initial load times with all layers enabled
- Holy mode is default, while evil mode is available
- Vertico minibuffer with fuzzy completion
- Tested on Linux, but should work also work fine anywhere for the most part.
- Tuned for ultimate performance using the latest gccemacs with native json parsing with eglot language server protocol  (not required, just recommended.)
- Treesitter enabled everywhere by default

  Spartan Emacs is not a starter kit. It does not teach Emacs. If you are new, and please begin by checking out ~M-x help-with-tutorial~.
  ~M-x~ means (~Alt~ + ~x~) and then ~help-with-tutorial~ Return (enter) to begin. One might follow up with ~An Introduction to Programming in Emacs Lisp~
  additionally. The manuals may all be found at https://www.gnu.org/software/emacs/manual/

*** QUICK INSTALL

#+BEGIN_SRC bash
  git clone https://github.com/a-schaefers/spartan-emacs.git ~/.emacs.d
#+END_SRC

*** HOW TO UPDATE

Layers use pinned packages via Straight.el and are periodically updated.

1. *git pull*

2. *M-x straight-thaw-versions*

3. *Restart Emacs*

*** LAYERS

- Edit ~.emacs.d/spartan.el~ to configure the theme, fonts, and  additional layers and packages, then restart

**** HOW LAYERS WORK

1. init.el (among other things) auto-generates a default ~/.emacs.d/spartan.el

   This configuration file is not stored in our Git, but you might want to add it in to yours.

   It may freely be modified by the user.

*** MINIMAL LANGUAGE LAYERS PRECONFIGURED

The idea here is to provide everywhere the get up and going configuration, this means proper syntax support,
auto-completion and find definition, etc. via eglot's minimal language server protocol implementation.
Some of the language modes also include repls. Debugging is provided within many of the languages themselves,
e.g. Python has pdb. With C, one may use ~M-x gdb~, etc.

With compiled languages, one might use M-x cc and set the compile-command to something instead of make if needed, etc.

*** BINDS

- Default emacs binds (unless you enable evil.)

- Short M-x aliases

  - M-x git  (magit)
  - M-x pro  (projectile-commander)
  - M-x sh   (better-shell)
  - M-x lint (flymake)
  - M-x cc   (compile-command)
  - etc...

- Language mode specific binds should be handled by the mode upstream or by the individual user with overrides in spartan.el
